///////////////////////////////////////////////////////////
//  Author.cs
//  Implementation of the Class Author
//  Generated by Enterprise Architect
//  Created on:      02-ÎåÔÂ-2012 16:20:55
//  Original author: lanfengqi
///////////////////////////////////////////////////////////


using System;
using nl.siegmann.epublib.util;

namespace nl.siegmann.epublib.domain
{
    /// <summary>
    /// Represents one of the authors of the book
    /// </summary>
    [Serializable]
    public class Author
    {
        private string firstname;
        private string lastname;
        private Relator relator = Relator.AUTHOR;
        private static readonly long serialVersionUID = 6663408501416574200L;

        public Author(string singleName)
            : this("", singleName)
        {

        }

        public Author(string firstname, string lastname)
        {
            this.firstname = firstname;
            this.lastname = lastname;
        }

        public bool equals(Object authorObject)
        {
            if (!(authorObject.GetType() == typeof(Author)))
            {
                return false;
            }
            var other = (Author)authorObject;
            return StringUtil.equals(firstname, other.firstname)
             && StringUtil.equals(lastname, other.lastname);
        }

        public string getFirstname()
        {
            return this.firstname;
        }

        public string getLastname()
        {
            return this.lastname;
        }

        public Relator getRelator()
        {
            return new Relator();
        }

        public int hashCode()
        {
            return StringUtil.hashCode(new string[] { firstname, lastname });
        }

        public void setFirstname(string firstname)
        {
            this.firstname = firstname;
        }

        public void setLastname(string lastname)
        {
            this.lastname = lastname;
        }

        public void setRelator(Relator relator)
        {
            this.relator = relator;
        }

        public Relator setRole(string code)
        {
            return this.relator;
        }

        public string toString()
        {
            return lastname + ", " + firstname;
        }

    }//end Author

}//end namespace domain