///////////////////////////////////////////////////////////
//  Metadata.cs
//  Implementation of the Class Metadata
//  Generated by Enterprise Architect
//  Created on:      02-ÎåÔÂ-2012 16:21:03
//  Original author: lanfengqi
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using nl.siegmann.epublib.domain;
namespace nl.siegmann.epublib.domain {
	/// <summary>
	/// A Book's collection of Metadata. In the future it should contain all Dublin
	/// Core attributes, for now it contains a set of often-used ones.
	/// </summary>
	[Serializable]
	public class Metadata  {

        private List<Author> authors = new List<Author>();
		private bool autoGeneratedId = true;
        private List<Author> contributors = new List<Author>();
		private Resource coverImage;
        private List<Date> dates = new List<Date>();
		private static readonly string DEFAULT_LANGUAGE = "en";
        private List<String> descriptions = new List<String>();
		//private string format = MediatypeService.EPUB.getName();
        private List<Identifier> identifiers = new List<Identifier>();
		private string language = DEFAULT_LANGUAGE;
        private Dictionary<string, string> otherProperties = new Dictionary<string, string>();
        private List<String> publishers = new List<String>();
        private List<String> rights = new List<String>();
		private static readonly long serialVersionUID = -2437262888962149444L;
        private List<String> subjects = new List<String>();
        private List<String> titles = new List<String>();
        private List<String> types = new List<String>();



		~Metadata(){

		}

		public virtual void Dispose(){

		}

		public Metadata(){

		}

		/// 
		/// <param name="author"></param>
		public Author addAuthor(Author author){

			return null;
		}

		/// 
		/// <param name="contributor"></param>
		public Author addContributor(Author contributor){

			return null;
		}

		/// 
		/// <param name="date"></param>
		public Date addDate(Date date){

			return null;
		}

		/// 
		/// <param name="description"></param>
		public string addDescription(string description){

			return "";
		}

		/// 
		/// <param name="identifier"></param>
		public Identifier addIdentifier(Identifier identifier){

			return null;
		}

		/// 
		/// <param name="publisher"></param>
		public string addPublisher(string publisher){

			return "";
		}

		/// 
		/// <param name="title"></param>
		public string addTitle(string title){

			return "";
		}

		/// 
		/// <param name="type"></param>
		public string addType(string type){

			return "";
		}

		public string Defate_Language{
			get{
                return language;
			}
			set{
                language = value;
			}
		}

		public List<Author> getAuthors(){

			return null;
		}

		public List<Author> getContributors(){

			return null;
		}

		public List<Date> getDates(){

			return null;
		}

		public List<String> getDescriptions(){

			return null;
		}

		/// <summary>
		/// Gets the first non-blank title of the book. Will return "" if no title found.
		/// </summary>
		public string getFirstTitle(){

			return "";
		}

		public string getFormat(){

			return "";
		}

		public List<Identifier> getIdentifiers(){

			return null;
		}

		public string getLanguage(){

			return "";
		}

		/// <summary>
		/// Metadata properties not hard-coded like the author, title, etc.
		/// </summary>
        //public Map<QName, String> getOtherProperties(){

        //    return null;
        //}

		public List<String> getPublishers(){

			return null;
		}

		public List<String> getRights(){

			return null;
		}

		public List<String> getSubjects(){

			return null;
		}

		public List<String> getTitles(){

			return null;
		}

		public List<String> getTypes(){

			return null;
		}

		public bool isAutoGeneratedId(){

			return false;
		}

		/// 
		/// <param name="authors"></param>
		public void setAuthors(List<Author> authors){

		}

		/// 
		/// <param name="contributors"></param>
		public void setContributors(List<Author> contributors){

		}

		/// 
		/// <param name="dates"></param>
		public void setDates(List<Date> dates){

		}

		/// 
		/// <param name="descriptions"></param>
		public void setDescriptions(List<String> descriptions){

		}

		/// 
		/// <param name="format"></param>
		public void setFormat(string format){

		}

		/// 
		/// <param name="identifiers"></param>
		public void setIdentifiers(List<Identifier> identifiers){

		}

		/// 
		/// <param name="language"></param>
		public void setLanguage(string language){

		}

		/// 
		/// <param name="otherProperties"></param>
		public void setOtherProperties(Dictionary<string, string> otherProperties){

		}

		/// 
		/// <param name="publishers"></param>
		public void setPublishers(List<String> publishers){

		}

		/// 
		/// <param name="rights"></param>
		public void setRights(List<String> rights){

		}

		/// 
		/// <param name="subjects"></param>
		public void setSubjects(List<String> subjects){

		}

		/// 
		/// <param name="titles"></param>
		public void setTitles(List<String> titles){

		}

		/// 
		/// <param name="types"></param>
		public void setTypes(List<String> types){

		}

	}//end Metadata

}//end namespace domain