///////////////////////////////////////////////////////////
//  Relator.cs
//  Implementation of the Class Relator
//  Generated by Enterprise Architect
//  Created on:      02-ŒÂ‘¬-2012 16:21:03
//  Original author: lanfengqi
///////////////////////////////////////////////////////////




namespace nl.siegmann.epublib.domain {
	/// <summary>
	/// A relator denotes which role a certain individual had in the
	/// creation/modification of the ebook.  Examples are 'creator', 'blurb writer',
	/// etc.  This is contains the complete Library of Concress relator list.
	/// </summary>
	/// <see>http://www.loc.gov/marc/relators/relaterm.html</see>
	public enum Relator : int {

		/// <summary>
		/// Use for a person or organization who principally exhibits acting skills in a
		/// musical or dramatic presentation or entertainment.
		/// </summary>
		ACTOR,
		/// <summary>
		/// Use for a person or organization who 1) reworks a musical composition, usually
		/// for a different medium, or 2) rewrites novels or stories for motion pictures or
		/// other audiovisual medium.
		/// </summary>
		ADAPTER,
		/// <summary>
		/// Use for a person or organization that reviews, examines and interprets data or
		/// information in a specific area.
		/// </summary>
		ANALYST,
		/// <summary>
		/// Use for a person or organization who draws the two-dimensional figures,
		/// manipulates the three dimensional objects and/or also programs the computer to
		/// move objects and images for the purpose of animated film processing. Animation
		/// cameras, stands, celluloid screens, transparencies and inks are some of the
		/// tools of the animator.
		/// </summary>
		ANIMATOR,
		/// <summary>
		/// Use for a person who writes manuscript annotations on a printed item.
		/// </summary>
		ANNOTATOR,
		/// <summary>
		/// Use for a person or organization responsible for the submission of an
		/// application or who is named as eligible for the results of the processing of
		/// the application (e.g., bestowing of rights, reward, title, position).
		/// </summary>
		APPLICANT,
		/// <summary>
		/// Use for a person or organization who designs structures or oversees their
		/// construction.
		/// </summary>
		ARCHITECT,
		/// <summary>
		/// Use for a person or organization who transcribes a musical composition, usually
		/// for a different medium from that of the original; in an arrangement the musical
		/// substance remains essentially unchanged.
		/// </summary>
		ARRANGER,
		/// <summary>
		/// Use for a person (e.g., a painter or sculptor) who makes copies of works of
		/// visual art.
		/// </summary>
		ART_COPYIST,
		/// <summary>
		/// Use for a person (e.g., a painter) or organization who conceives, and perhaps
		/// also implements, an original graphic design or work of art, if specific codes
		/// (e.g., [egr], [etr]) are not desired. For book illustrators, prefer Illustrator
		/// [ill].
		/// </summary>
		ARTIST,
		/// <summary>
		/// Use for a person responsible for controlling the development of the artistic
		/// style of an entire production, including the choice of works to be presented
		/// and selection of senior production staff.
		/// </summary>
		ARTISTIC_DIRECTOR,
		/// <summary>
		/// Use for a person or organization to whom a license for printing or publishing
		/// has been transferred.
		/// </summary>
		ASSIGNEE,
		/// <summary>
		/// Use for a person or organization associated with or found in an item or
		/// collection, which cannot be determined to be that of a Former owner [fmo] or
		/// other designated relator indicative of provenance.
		/// </summary>
		ASSOCIATED_NAME,
		/// <summary>
		/// Use for an author, artist, etc., relating him/her to a work for which there is
		/// or once was substantial authority for designating that person as author,
		/// creator, etc. of the work.
		/// </summary>
		ATTRIBUTED_NAME,
		/// <summary>
		/// Use for a person or organization in charge of the estimation and public
		/// auctioning of goods, particularly books, artistic works, etc.
		/// </summary>
		AUCTIONEER,
		/// <summary>
		/// Use for a person or organization chiefly responsible for the intellectual or
		/// artistic content of a work, usually printed text. This term may also be used
		/// when more than one person or body bears such responsibility.
		/// </summary>
		AUTHOR,
		/// <summary>
		/// Use for a person or organization whose work is largely quoted or extracted in
		/// works to which he or she did not contribute directly. Such quotations are found
		/// particularly in exhibition catalogs, collections of photographs, etc.
		/// </summary>
		AUTHOR_IN_QUOTATIONS_OR_TEXT_EXTRACTS,
		/// <summary>
		/// Use for a person or organization responsible for an afterword, postface,
		/// colophon, etc. but who is not the chief author of a work.
		/// </summary>
		AUTHOR_OF_AFTERWORD_COLOPHON_ETC,
		/// <summary>
		/// Use for a person or organization responsible for the dialog or spoken
		/// commentary for a screenplay or sound recording.
		/// </summary>
		AUTHOR_OF_DIALOG,
		/// <summary>
		/// Use for a person or organization responsible for an introduction, preface,
		/// foreword, or other critical introductory matter, but who is not the chief
		/// author.
		/// </summary>
		AUTHOR_OF_INTRODUCTION_ETC,
		/// <summary>
		/// Use for a person or organization responsible for a motion picture screenplay,
		/// dialog, spoken commentary, etc.
		/// </summary>
		AUTHOR_OF_SCREENPLAY_ETC,
		/// <summary>
		/// Use for a person or organization responsible for a work upon which the work
		/// represented by the catalog record is based. This may be appropriate for
		/// adaptations, sequels, continuations, indexes, etc.
		/// </summary>
		BIBLIOGRAPHIC_ANTECEDENT,
		/// <summary>
		/// Use for a person or organization responsible for the binding of printed or
		/// manuscript materials.
		/// </summary>
		BINDER,
		/// <summary>
		/// Use for a person or organization responsible for the binding design of a book,
		/// including the type of binding, the type of materials used, and any decorative
		/// aspects of the binding.
		/// </summary>
		BINDING_DESIGNER,
		/// <summary>
		/// Use for the named entity responsible for writing a commendation or testimonial
		/// for a work, which appears on or within the publication itself, frequently on
		/// the back or dust jacket of print publications or on advertising material for
		/// all media.
		/// </summary>
		BLURB_WRITER,
		/// <summary>
		/// Use for a person or organization responsible for the entire graphic design of a
		/// book, including arrangement of type and illustration, choice of materials, and
		/// process used.
		/// </summary>
		BOOK_DESIGNER,
		/// <summary>
		/// Use for a person or organization responsible for the production of books and
		/// other print media, if specific codes (e.g., [bkd], [egr], [tyd], [prt]) are not
		/// desired.
		/// </summary>
		BOOK_PRODUCER,
		/// <summary>
		/// Use for a person or organization responsible for the design of flexible covers
		/// designed for or published with a book, including the type of materials used,
		/// and any decorative aspects of the bookjacket.
		/// </summary>
		BOOKJACKET_DESIGNER,
		/// <summary>
		/// Use for a person or organization responsible for the design of a book owner's
		/// identification label that is most commonly pasted to the inside front cover of
		/// a book.
		/// </summary>
		BOOKPLATE_DESIGNER,
		/// <summary>
		/// Use for a person or organization who makes books and other bibliographic
		/// materials available for purchase. Interest in the materials is primarily
		/// lucrative.
		/// </summary>
		BOOKSELLER,
		/// <summary>
		/// Use for a person or organization who writes in an artistic hand, usually as a
		/// copyist and or engrosser.
		/// </summary>
		CALLIGRAPHER,
		/// <summary>
		/// Use for a person or organization responsible for the creation of maps and other
		/// cartographic materials.
		/// </summary>
		CARTOGRAPHER,
		/// <summary>
		/// Use for a censor, bowdlerizer, expurgator, etc., official or private.
		/// </summary>
		CENSOR,
		/// <summary>
		/// Use for a person or organization who composes or arranges dances or other
		/// movements (e.g., "master of swords") for a musical or dramatic presentation or
		/// entertainment.
		/// </summary>
		CHOREOGRAPHER,
		/// <summary>
		/// Use for a person or organization who is in charge of the images captured for a
		/// motion picture film. The cinematographer works under the supervision of a
		/// director, and may also be referred to as director of photography. Do not
		/// confuse with videographer.
		/// </summary>
		CINEMATOGRAPHER,
		/// <summary>
		/// Use for a person or organization for whom another person or organization is
		/// acting.
		/// </summary>
		CLIENT,
		/// <summary>
		/// Use for a person or organization that takes a limited part in the elaboration
		/// of a work of another person or organization that brings complements (e.g.,
		/// appendices, notes) to the work.
		/// </summary>
		COLLABORATOR,
		/// <summary>
		/// Use for a person or organization who has brought together material from various
		/// sources that has been arranged, described, and cataloged as a collection. A
		/// collector is neither the creator of the material nor a person to whom
		/// manuscripts in the collection may have been addressed.
		/// </summary>
		COLLECTOR,
		/// <summary>
		/// Use for a person or organization responsible for the production of photographic
		/// prints from film or other colloid that has ink-receptive and ink-repellent
		/// surfaces.
		/// </summary>
		COLLOTYPER,
		/// <summary>
		/// Use for the named entity responsible for applying color to drawings, prints,
		/// photographs, maps, moving images, etc.
		/// </summary>
		COLORIST,
		/// <summary>
		/// Use for a person or organization who provides interpretation, analysis, or a
		/// discussion of the subject matter on a recording, motion picture, or other
		/// audiovisual medium.
		/// </summary>
		COMMENTATOR,
		/// <summary>
		/// Use for a person or organization responsible for the commentary or explanatory
		/// notes about a text. For the writer of manuscript annotations in a printed book,
		/// use Annotator [ann].
		/// </summary>
		COMMENTATOR_FOR_WRITTEN_TEXT,
		/// <summary>
		/// Use for a person or organization who produces a work or publication by
		/// selecting and putting together material from the works of various persons or
		/// bodies.
		/// </summary>
		COMPILER,
		/// <summary>
		/// Use for the party who applies to the courts for redress, usually in an equity
		/// proceeding.
		/// </summary>
		COMPLAINANT,
		/// <summary>
		/// Use for a complainant who takes an appeal from one court or jurisdiction to
		/// another to reverse the judgment, usually in an equity proceeding.
		/// </summary>
		COMPLAINANT_APPELLANT,
		/// <summary>
		/// Use for a complainant against whom an appeal is taken from one court or
		/// jurisdiction to another to reverse the judgment, usually in an equity
		/// proceeding.
		/// </summary>
		COMPLAINANT_APPELLEE,
		/// <summary>
		/// Use for a person or organization who creates a musical work, usually a piece of
		/// music in manuscript or printed form.
		/// </summary>
		COMPOSER,
		/// <summary>
		/// Use for a person or organization responsible for the creation of metal slug, or
		/// molds made of other materials, used to produce the text and images in printed
		/// matter.
		/// </summary>
		COMPOSITOR,
		/// <summary>
		/// Use for a person or organization responsible for the original idea on which a
		/// work is based, this includes the scientific author of an audio-visual item and
		/// the conceptor of an advertisement.
		/// </summary>
		CONCEPTOR,
		/// <summary>
		/// Use for a person who directs a performing group (orchestra, chorus, opera, etc.
		/// ) in a musical or dramatic presentation or entertainment.
		/// </summary>
		CONDUCTOR,
		/// <summary>
		/// Use for the named entity responsible for documenting, preserving, or treating
		/// printed or manuscript material, works of art, artifacts, or other media.
		/// </summary>
		CONSERVATOR,
		/// <summary>
		/// Use for a person or organization relevant to a resource, who is called upon for
		/// professional advice or services in a specialized field of knowledge or training.
		/// 
		/// </summary>
		CONSULTANT,
		/// <summary>
		/// Use for a person or organization relevant to a resource, who is engaged
		/// specifically to provide an intellectual overview of a strategic or operational
		/// task and by analysis, specification, or instruction, to create or propose a
		/// cost-effective course of action or solution.
		/// </summary>
		CONSULTANT_TO_A_PROJECT,
		/// <summary>
		/// Use for the party who opposes, resists, or disputes, in a court of law, a claim,
		/// decision, result, etc.
		/// </summary>
		CONTESTANT,
		/// <summary>
		/// Use for a contestant who takes an appeal from one court of law or jurisdiction
		/// to another to reverse the judgment.
		/// </summary>
		CONTESTANT_APPELLANT,
		/// <summary>
		/// Use for a contestant against whom an appeal is taken from one court of law or
		/// jurisdiction to another to reverse the judgment.
		/// </summary>
		CONTESTANT_APPELLEE,
		/// <summary>
		/// Use for the party defending a claim, decision, result, etc. being opposed,
		/// resisted, or disputed in a court of law.
		/// </summary>
		CONTESTEE,
		/// <summary>
		/// Use for a contestee who takes an appeal from one court or jurisdiction to
		/// another to reverse the judgment.
		/// </summary>
		CONTESTEE_APPELLANT,
		/// <summary>
		/// Use for a contestee against whom an appeal is taken from one court or
		/// jurisdiction to another to reverse the judgment.
		/// </summary>
		CONTESTEE_APPELLEE,
		/// <summary>
		/// Use for a person or organization relevant to a resource, who enters into a
		/// contract with another person or organization to perform a specific task.
		/// </summary>
		CONTRACTOR,
		/// <summary>
		/// Use for a person or organization one whose work has been contributed to a
		/// larger work, such as an anthology, serial publication, or other compilation of
		/// individual works. Do not use if the sole function in relation to a work is as
		/// author, editor, compiler or translator.
		/// </summary>
		CONTRIBUTOR,
		/// <summary>
		/// Use for a person or organization listed as a copyright owner at the time of
		/// registration. Copyright can be granted or later transferred to another person
		/// or organization, at which time the claimant becomes the copyright holder.
		/// </summary>
		COPYRIGHT_CLAIMANT,
		/// <summary>
		/// Use for a person or organization to whom copy and legal rights have been
		/// granted or transferred for the intellectual content of a work. The copyright
		/// holder, although not necessarily the creator of the work, usually has the
		/// exclusive right to benefit financially from the sale and use of the work to
		/// which the associated copyright protection applies.
		/// </summary>
		COPYRIGHT_HOLDER,
		/// <summary>
		/// Use for a person or organization who is a corrector of manuscripts, such as the
		/// scriptorium official who corrected the work of a scribe. For printed matter,
		/// use Proofreader.
		/// </summary>
		CORRECTOR,
		/// <summary>
		/// Use for a person or organization who was either the writer or recipient of a
		/// letter or other communication.
		/// </summary>
		CORRESPONDENT,
		/// <summary>
		/// Use for a person or organization who designs or makes costumes, fixes hair, etc.
		/// , for a musical or dramatic presentation or entertainment.
		/// </summary>
		COSTUME_DESIGNER,
		/// <summary>
		/// Use for a person or organization responsible for the graphic design of a book
		/// cover, album cover, slipcase, box, container, etc. For a person or organization
		/// responsible for the graphic design of an entire book, use Book designer; for
		/// book jackets, use Bookjacket designer.
		/// </summary>
		COVER_DESIGNER,
		/// <summary>
		/// Use for a person or organization responsible for the intellectual or artistic
		/// content of a work.
		/// </summary>
		CREATOR,
		/// <summary>
		/// Use for a person or organization responsible for conceiving and organizing an
		/// exhibition.
		/// </summary>
		CURATOR_OF_AN_EXHIBITION,
		/// <summary>
		/// Use for a person or organization who principally exhibits dancing skills in a
		/// musical or dramatic presentation or entertainment.
		/// </summary>
		DANCER,
		/// <summary>
		/// Use for a person or organization that submits data for inclusion in a database
		/// or other collection of data.
		/// </summary>
		DATA_CONTRIBUTOR,
		/// <summary>
		/// Use for a person or organization responsible for managing databases or other
		/// data sources.
		/// </summary>
		DATA_MANAGER,
		/// <summary>
		/// Use for a person or organization to whom a book, manuscript, etc., is dedicated
		/// (not the recipient of a gift).
		/// </summary>
		DEDICATEE,
		/// <summary>
		/// Use for the author of a dedication, which may be a formal statement or in
		/// epistolary or verse form.
		/// </summary>
		DEDICATOR,
		/// <summary>
		/// Use for the party defending or denying allegations made in a suit and against
		/// whom relief or recovery is sought in the courts, usually in a legal action.
		/// </summary>
		DEFENDANT,
		/// <summary>
		/// Use for a defendant who takes an appeal from one court or jurisdiction to
		/// another to reverse the judgment, usually in a legal action.
		/// </summary>
		DEFENDANT_APPELLANT,
		/// <summary>
		/// Use for a defendant against whom an appeal is taken from one court or
		/// jurisdiction to another to reverse the judgment, usually in a legal action.
		/// </summary>
		DEFENDANT_APPELLEE,
		/// <summary>
		/// Use for the organization granting a degree for which the thesis or dissertation
		/// described was presented.
		/// </summary>
		DEGREE_GRANTOR,
		/// <summary>
		/// Use for a person or organization executing technical drawings from others'
		/// designs.
		/// </summary>
		DELINEATOR,
		/// <summary>
		/// Use for an entity depicted or portrayed in a work, particularly in a work of
		/// art.
		/// </summary>
		DEPICTED,
		/// <summary>
		/// Use for a person or organization placing material in the physical custody of a
		/// library or repository without transferring the legal title.
		/// </summary>
		DEPOSITOR,
		/// <summary>
		/// Use for a person or organization responsible for the design if more specific
		/// codes (e.g., [bkd], [tyd]) are not desired.
		/// </summary>
		DESIGNER,
		/// <summary>
		/// Use for a person or organization who is responsible for the general management
		/// of a work or who supervises the production of a performance for stage, screen,
		/// or sound recording.
		/// </summary>
		DIRECTOR,
		/// <summary>
		/// Use for a person who presents a thesis for a university or higher-level
		/// educational degree.
		/// </summary>
		DISSERTANT,
		/// <summary>
		/// Use for the name of a place from which a resource, e.g., a serial, is
		/// distributed.
		/// </summary>
		DISTRIBUTION_PLACE,
		/// <summary>
		/// Use for a person or organization that has exclusive or shared marketing rights
		/// for an item.
		/// </summary>
		DISTRIBUTOR,
		/// <summary>
		/// Use for a person or organization who is the donor of a book, manuscript, etc.,
		/// to its present owner. Donors to previous owners are designated as Former owner
		/// [fmo] or Inscriber [ins].
		/// </summary>
		DONOR,
		/// <summary>
		/// Use for a person or organization who prepares artistic or technical drawings.
		/// </summary>
		DRAFTSMAN,
		/// <summary>
		/// Use for a person or organization to which authorship has been dubiously or
		/// incorrectly ascribed.
		/// </summary>
		DUBIOUS_AUTHOR,
		/// <summary>
		/// Use for a person or organization who prepares for publication a work not
		/// primarily his/her own, such as by elucidating text, adding introductory or
		/// other critical matter, or technically directing an editorial staff.
		/// </summary>
		EDITOR,
		/// <summary>
		/// Use for a person responsible for setting up a lighting rig and focusing the
		/// lights for a production, and running the lighting at a performance.
		/// </summary>
		ELECTRICIAN,
		/// <summary>
		/// Use for a person or organization who creates a duplicate printing surface by
		/// pressure molding and electrodepositing of metal that is then backed up with
		/// lead for printing.
		/// </summary>
		ELECTROTYPER,
		/// <summary>
		/// Use for a person or organization that is responsible for technical planning and
		/// design, particularly with construction.
		/// </summary>
		ENGINEER,
		/// <summary>
		/// Use for a person or organization who cuts letters, figures, etc. on a surface,
		/// such as a wooden or metal plate, for printing.
		/// </summary>
		ENGRAVER,
		/// <summary>
		/// Use for a person or organization who produces text or images for printing by
		/// subjecting metal, glass, or some other surface to acid or the corrosive action
		/// of some other substance.
		/// </summary>
		ETCHER,
		/// <summary>
		/// Use for the name of the place where an event such as a conference or a concert
		/// took place.
		/// </summary>
		EVENT_PLACE,
		/// <summary>
		/// Use for a person or organization in charge of the description and appraisal of
		/// the value of goods, particularly rare items, works of art, etc.
		/// </summary>
		EXPERT,
		/// <summary>
		/// Use for a person or organization that executed the facsimile.
		/// </summary>
		FACSIMILIST,
		/// <summary>
		/// Use for a person or organization that manages or supervises the work done to
		/// collect raw data or do research in an actual setting or environment (typically
		/// applies to the natural and social sciences).
		/// </summary>
		FIELD_DIRECTOR,
		/// <summary>
		/// Use for a person or organization who is an editor of a motion picture film.
		/// This term is used regardless of the medium upon which the motion picture is
		/// produced or manufactured (e.g., acetate film, video tape).
		/// </summary>
		FILM_EDITOR,
		/// <summary>
		/// Use for a person or organization who is identified as the only party or the
		/// party of the first part. In the case of transfer of right, this is the assignor,
		/// transferor, licensor, grantor, etc. Multiple parties can be named jointly as
		/// the first party
		/// </summary>
		FIRST_PARTY,
		/// <summary>
		/// Use for a person or organization who makes or imitates something of value or
		/// importance, especially with the intent to defraud.
		/// </summary>
		FORGER,
		/// <summary>
		/// Use for a person or organization who owned an item at any time in the past.
		/// Includes those to whom the material was once presented. A person or
		/// organization giving the item to the present owner is designated as Donor [dnr]
		/// </summary>
		FORMER_OWNER,
		/// <summary>
		/// Use for a person or organization that furnished financial support for the
		/// production of the work.
		/// </summary>
		FUNDER,
		/// <summary>
		/// Use for a person responsible for geographic information system (GIS)
		/// development and integration with global positioning system data.
		/// </summary>
		GEOGRAPHIC_INFORMATION_SPECIALIST,
		/// <summary>
		/// Use for a person or organization in memory or honor of whom a book, manuscript,
		/// etc. is donated.
		/// </summary>
		HONOREE,
		/// <summary>
		/// Use for a person who is invited or regularly leads a program (often broadcast)
		/// that includes other guests, performers, etc. (e.g., talk show host).
		/// </summary>
		HOST,
		/// <summary>
		/// Use for a person or organization responsible for the decoration of a work
		/// (especially manuscript material) with precious metals or color, usually with
		/// elaborate designs and motifs.
		/// </summary>
		ILLUMINATOR,
		/// <summary>
		/// Use for a person or organization who conceives, and perhaps also implements, a
		/// design or illustration, usually to accompany a written text.
		/// </summary>
		ILLUSTRATOR,
		/// <summary>
		/// Use for a person who signs a presentation statement.
		/// </summary>
		INSCRIBER,
		/// <summary>
		/// Use for a person or organization who principally plays an instrument in a
		/// musical or dramatic presentation or entertainment.
		/// </summary>
		INSTRUMENTALIST,
		/// <summary>
		/// Use for a person or organization who is interviewed at a consultation or
		/// meeting, usually by a reporter, pollster, or some other information gathering
		/// agent.
		/// </summary>
		INTERVIEWEE,
		/// <summary>
		/// Use for a person or organization who acts as a reporter, pollster, or other
		/// information gathering agent in a consultation or meeting involving one or more
		/// individuals.
		/// </summary>
		INTERVIEWER,
		/// <summary>
		/// Use for a person or organization who first produces a particular useful item,
		/// or develops a new process for obtaining a known item or result.
		/// </summary>
		INVENTOR,
		/// <summary>
		/// Use for an institution that provides scientific analyses of material samples.
		/// </summary>
		LABORATORY,
		/// <summary>
		/// Use for a person or organization that manages or supervises work done in a
		/// controlled setting or environment.
		/// </summary>
		LABORATORY_DIRECTOR,
		/// <summary>
		/// Use for a person or organization whose work involves coordinating the
		/// arrangement of existing and proposed land features and structures.
		/// </summary>
		LANDSCAPE_ARCHITECT,
		/// <summary>
		/// Use to indicate that a person or organization takes primary responsibility for
		/// a particular activity or endeavor. Use with another relator term or code to
		/// show the greater importance this person or organization has regarding that
		/// particular role. If more than one relator is assigned to a heading, use the
		/// Lead relator only if it applies to all the relators.
		/// </summary>
		LEAD,
		/// <summary>
		/// Use for a person or organization permitting the temporary use of a book,
		/// manuscript, etc., such as for photocopying or microfilming.
		/// </summary>
		LENDER,
		/// <summary>
		/// Use for the party who files a libel in an ecclesiastical or admiralty case.
		/// </summary>
		LIBELANT,
		/// <summary>
		/// Use for a libelant who takes an appeal from one ecclesiastical court or
		/// admiralty to another to reverse the judgment.
		/// </summary>
		LIBELANT_APPELLANT,
		/// <summary>
		/// Use for a libelant against whom an appeal is taken from one ecclesiastical
		/// court or admiralty to another to reverse the judgment.
		/// </summary>
		LIBELANT_APPELLEE,
		/// <summary>
		/// Use for a party against whom a libel has been filed in an ecclesiastical court
		/// or admiralty.
		/// </summary>
		LIBELEE,
		/// <summary>
		/// Use for a libelee who takes an appeal from one ecclesiastical court or
		/// admiralty to another to reverse the judgment.
		/// </summary>
		LIBELEE_APPELLANT,
		/// <summary>
		/// Use for a libelee against whom an appeal is taken from one ecclesiastical court
		/// or admiralty to another to reverse the judgment.
		/// </summary>
		LIBELEE_APPELLEE,
		/// <summary>
		/// Use for a person or organization who is a writer of the text of an opera,
		/// oratorio, etc.
		/// </summary>
		LIBRETTIST,
		/// <summary>
		/// Use for a person or organization who is an original recipient of the right to
		/// print or publish.
		/// </summary>
		LICENSEE,
		/// <summary>
		/// Use for person or organization who is a signer of the license, imprimatur, etc.
		/// 
		/// </summary>
		LICENSOR,
		/// <summary>
		/// Use for a person or organization who designs the lighting scheme for a
		/// theatrical presentation, entertainment, motion picture, etc.
		/// </summary>
		LIGHTING_DESIGNER,
		/// <summary>
		/// Use for a person or organization who prepares the stone or plate for
		/// lithographic printing, including a graphic artist creating a design directly on
		/// the surface from which printing will be done.
		/// </summary>
		LITHOGRAPHER,
		/// <summary>
		/// Use for a person or organization who is a writer of the text of a song.
		/// </summary>
		LYRICIST,
		/// <summary>
		/// Use for a person or organization that makes an artifactual work (an object made
		/// or modified by one or more persons). Examples of artifactual works include
		/// vases, cannons or pieces of furniture.
		/// </summary>
		MANUFACTURER,
		/// <summary>
		/// Use for the named entity responsible for marbling paper, cloth, leather, etc.
		/// used in construction of a resource.
		/// </summary>
		MARBLER,
		/// <summary>
		/// Use for a person or organization performing the coding of SGML, HTML, or XML
		/// markup of metadata, text, etc.
		/// </summary>
		MARKUP_EDITOR,
		/// <summary>
		/// Use for a person or organization primarily responsible for compiling and
		/// maintaining the original description of a metadata set (e.g., geospatial
		/// metadata set).
		/// </summary>
		METADATA_CONTACT,
		/// <summary>
		/// Use for a person or organization responsible for decorations, illustrations,
		/// letters, etc. cut on a metal surface for printing or decoration.
		/// </summary>
		METAL_ENGRAVER,
		/// <summary>
		/// Use for a person who leads a program (often broadcast) where topics are
		/// discussed, usually with participation of experts in fields related to the
		/// discussion.
		/// </summary>
		MODERATOR,
		/// <summary>
		/// Use for a person or organization that supervises compliance with the contract
		/// and is responsible for the report and controls its distribution. Sometimes
		/// referred to as the grantee, or controlling agency.
		/// </summary>
		MONITOR,
		/// <summary>
		/// Use for a person who transcribes or copies musical notation
		/// </summary>
		MUSIC_COPYIST,
		/// <summary>
		/// Use for a person responsible for basic music decisions about a production,
		/// including coordinating the work of the composer, the sound editor, and sound
		/// mixers, selecting musicians, and organizing and/or conducting sound for
		/// rehearsals and performances.
		/// </summary>
		MUSICAL_DIRECTOR,
		/// <summary>
		/// Use for a person or organization who performs music or contributes to the
		/// musical content of a work when it is not possible or desirable to identify the
		/// function more precisely.
		/// </summary>
		MUSICIAN,
		/// <summary>
		/// Use for a person who is a speaker relating the particulars of an act,
		/// occurrence, or course of events.
		/// </summary>
		NARRATOR,
		/// <summary>
		/// Use for a person or organization responsible for opposing a thesis or
		/// dissertation.
		/// </summary>
		OPPONENT,
		/// <summary>
		/// Use for a person or organization responsible for organizing a meeting for which
		/// an item is the report or proceedings.
		/// </summary>
		ORGANIZER_OF_MEETING,
		/// <summary>
		/// Use for a person or organization performing the work, i.e., the name of a
		/// person or organization associated with the intellectual content of the work.
		/// This category does not include the publisher or personal affiliation, or
		/// sponsor except where it is also the corporate author.
		/// </summary>
		ORIGINATOR,
		/// <summary>
		/// Use for relator codes from other lists which have no equivalent in the MARC
		/// list or for terms which have not been assigned a code.
		/// </summary>
		OTHER,
		/// <summary>
		/// Use for a person or organization that currently owns an item or collection.
		/// </summary>
		OWNER,
		/// <summary>
		/// Use for a person or organization responsible for the production of paper,
		/// usually from wood, cloth, or other fibrous material.
		/// </summary>
		PAPERMAKER,
		/// <summary>
		/// Use for a person or organization that applied for a patent.
		/// </summary>
		PATENT_APPLICANT,
		/// <summary>
		/// Use for a person or organization that was granted the patent referred to by the
		/// item.
		/// </summary>
		PATENT_HOLDER,
		/// <summary>
		/// Use for a person or organization responsible for commissioning a work. Usually
		/// a patron uses his or her means or influence to support the work of artists,
		/// writers, etc. This includes those who commission and pay for individual works.
		/// </summary>
		PATRON,
		/// <summary>
		/// Use for a person or organization who exhibits musical or acting skills in a
		/// musical or dramatic presentation or entertainment, if specific codes for those
		/// functions ([act], [dnc], [itr], [voc], etc.) are not used. If specific codes
		/// are used, [prf] is used for a person whose principal skill is not known or
		/// specified.
		/// </summary>
		PERFORMER,
		/// <summary>
		/// Use for an authority (usually a government agency) that issues permits under
		/// which work is accomplished.
		/// </summary>
		PERMITTING_AGENCY,
		/// <summary>
		/// Use for a person or organization responsible for taking photographs, whether
		/// they are used in their original form or as reproductions.
		/// </summary>
		PHOTOGRAPHER,
		/// <summary>
		/// Use for the party who complains or sues in court in a personal action, usually
		/// in a legal proceeding.
		/// </summary>
		PLAINTIFF,
		/// <summary>
		/// Use for a plaintiff who takes an appeal from one court or jurisdiction to
		/// another to reverse the judgment, usually in a legal proceeding.
		/// </summary>
		PLAINTIFF_APPELLANT,
		/// <summary>
		/// Use for a plaintiff against whom an appeal is taken from one court or
		/// jurisdiction to another to reverse the judgment, usually in a legal proceeding.
		/// 
		/// </summary>
		PLAINTIFF_APPELLEE,
		/// <summary>
		/// Use for a person or organization responsible for the production of plates,
		/// usually for the production of printed images and/or text.
		/// </summary>
		PLATEMAKER,
		/// <summary>
		/// Use for a person or organization who prints texts, whether from type or plates.
		/// 
		/// </summary>
		PRINTER,
		/// <summary>
		/// Use for a person or organization who prints illustrations from plates.
		/// </summary>
		PRINTER_OF_PLATES,
		/// <summary>
		/// Use for a person or organization who makes a relief, intaglio, or planographic
		/// printing surface.
		/// </summary>
		PRINTMAKER,
		/// <summary>
		/// Use for a person or organization primarily responsible for performing or
		/// initiating a process, such as is done with the collection of metadata sets.
		/// </summary>
		PROCESS_CONTACT,
		/// <summary>
		/// Use for a person or organization responsible for the making of a motion picture,
		/// including business aspects, management of the productions, and the commercial
		/// success of the work.
		/// </summary>
		PRODUCER,
		/// <summary>
		/// Use for a person responsible for all technical and business matters in a
		/// production.
		/// </summary>
		PRODUCTION_MANAGER,
		/// <summary>
		/// Use for a person or organization associated with the production (props,
		/// lighting, special effects, etc.) of a musical or dramatic presentation or
		/// entertainment.
		/// </summary>
		PRODUCTION_PERSONNEL,
		/// <summary>
		/// Use for a person or organization responsible for the creation and/or
		/// maintenance of computer program design documents, source code, and machine-
		/// executable digital files and supporting documentation.
		/// </summary>
		PROGRAMMER,
		/// <summary>
		/// Use for a person or organization with primary responsibility for all essential
		/// aspects of a project, or that manages a very large project that demands senior
		/// level responsibility, or that has overall responsibility for managing projects,
		/// or provides overall direction to a project manager.
		/// </summary>
		PROJECT_DIRECTOR,
		/// <summary>
		/// Use for a person who corrects printed matter. For manuscripts, use Corrector
		/// [crr].
		/// </summary>
		PROOFREADER,
		/// <summary>
		/// Use for the name of the place where a resource is published.
		/// </summary>
		PUBLICATION_PLACE,
		/// <summary>
		/// Use for a person or organization that makes printed matter, often text, but
		/// also printed music, artwork, etc. available to the public.
		/// </summary>
		PUBLISHER,
		/// <summary>
		/// Use for a person or organization who presides over the elaboration of a
		/// collective work to ensure its coherence or continuity. This includes editors-in-
		/// chief, literary editors, editors of series, etc.
		/// </summary>
		PUBLISHING_DIRECTOR,
		/// <summary>
		/// Use for a person or organization who manipulates, controls, or directs puppets
		/// or marionettes in a musical or dramatic presentation or entertainment.
		/// </summary>
		PUPPETEER,
		/// <summary>
		/// Use for a person or organization to whom correspondence is addressed.
		/// </summary>
		RECIPIENT,
		/// <summary>
		/// Use for a person or organization who supervises the technical aspects of a
		/// sound or video recording session.
		/// </summary>
		RECORDING_ENGINEER,
		/// <summary>
		/// Use for a person or organization who writes or develops the framework for an
		/// item without being intellectually responsible for its content.
		/// </summary>
		REDACTOR,
		/// <summary>
		/// Use for a person or organization who prepares drawings of architectural designs
		/// (i.e., renderings) in accurate, representational perspective to show what the
		/// project will look like when completed.
		/// </summary>
		RENDERER,
		/// <summary>
		/// Use for a person or organization who writes or presents reports of news or
		/// current events on air or in print.
		/// </summary>
		REPORTER,
		/// <summary>
		/// Use for an agency that hosts data or material culture objects and provides
		/// services to promote long term, consistent and shared use of those data or
		/// objects.
		/// </summary>
		REPOSITORY,
		/// <summary>
		/// Use for a person who directed or managed a research project.
		/// </summary>
		RESEARCH_TEAM_HEAD,
		/// <summary>
		/// Use for a person who participated in a research project but whose role did not
		/// involve direction or management of it.
		/// </summary>
		RESEARCH_TEAM_MEMBER,
		/// <summary>
		/// Use for a person or organization responsible for performing research.
		/// </summary>
		RESEARCHER,
		/// <summary>
		/// Use for the party who makes an answer to the courts pursuant to an application
		/// for redress, usually in an equity proceeding.
		/// </summary>
		RESPONDENT,
		/// <summary>
		/// Use for a respondent who takes an appeal from one court or jurisdiction to
		/// another to reverse the judgment, usually in an equity proceeding.
		/// </summary>
		RESPONDENT_APPELLANT,
		/// <summary>
		/// Use for a respondent against whom an appeal is taken from one court or
		/// jurisdiction to another to reverse the judgment, usually in an equity
		/// proceeding.
		/// </summary>
		RESPONDENT_APPELLEE,
		/// <summary>
		/// Use for a person or organization legally responsible for the content of the
		/// published material.
		/// </summary>
		RESPONSIBLE_PARTY,
		/// <summary>
		/// Use for a person or organization, other than the original choreographer or
		/// director, responsible for restaging a choreographic or dramatic work and who
		/// contributes minimal new content.
		/// </summary>
		RESTAGER,
		/// <summary>
		/// Use for a person or organization responsible for the review of a book, motion
		/// picture, performance, etc.
		/// </summary>
		REVIEWER,
		/// <summary>
		/// Use for a person or organization responsible for parts of a work, often
		/// headings or opening parts of a manuscript, that appear in a distinctive color,
		/// usually red.
		/// </summary>
		RUBRICATOR,
		/// <summary>
		/// Use for a person or organization who is the author of a motion picture
		/// screenplay.
		/// </summary>
		SCENARIST,
		/// <summary>
		/// Use for a person or organization who brings scientific, pedagogical, or
		/// historical competence to the conception and realization on a work, particularly
		/// in the case of audio-visual items.
		/// </summary>
		SCIENTIFIC_ADVISOR,
		/// <summary>
		/// Use for a person who is an amanuensis and for a writer of manuscripts proper.
		/// For a person who makes pen-facsimiles, use Facsimilist [fac].
		/// </summary>
		SCRIBE,
		/// <summary>
		/// Use for a person or organization who models or carves figures that are three-
		/// dimensional representations.
		/// </summary>
		SCULPTOR,
		/// <summary>
		/// Use for a person or organization who is identified as the party of the second
		/// part. In the case of transfer of right, this is the assignee, transferee,
		/// licensee, grantee, etc. Multiple parties can be named jointly as the second
		/// party.
		/// </summary>
		SECOND_PARTY,
		/// <summary>
		/// Use for a person or organization who is a recorder, redactor, or other person
		/// responsible for expressing the views of a organization.
		/// </summary>
		SECRETARY,
		/// <summary>
		/// Use for a person or organization who translates the rough sketches of the art
		/// director into actual architectural structures for a theatrical presentation,
		/// entertainment, motion picture, etc. Set designers draw the detailed guides and
		/// specifications for building the set.
		/// </summary>
		SET_DESIGNER,
		/// <summary>
		/// Use for a person whose signature appears without a presentation or other
		/// statement indicative of provenance. When there is a presentation statement, use
		/// Inscriber [ins].
		/// </summary>
		SIGNER,
		/// <summary>
		/// Use for a person or organization who uses his/her/their voice with or without
		/// instrumental accompaniment to produce music. A performance may or may not
		/// include actual words.
		/// </summary>
		SINGER,
		/// <summary>
		/// Use for a person who produces and reproduces the sound score (both live and
		/// recorded), the installation of microphones, the setting of sound levels, and
		/// the coordination of sources of sound for a production.
		/// </summary>
		SOUND_DESIGNER,
		/// <summary>
		/// Use for a person who participates in a program (often broadcast) and makes a
		/// formalized contribution or presentation generally prepared in advance.
		/// </summary>
		SPEAKER,
		/// <summary>
		/// Use for a person or organization that issued a contract or under the auspices
		/// of which a work has been written, printed, published, etc.
		/// </summary>
		SPONSOR,
		/// <summary>
		/// Use for a person who is in charge of everything that occurs on a performance
		/// stage, and who acts as chief of all crews and assistant to a director during
		/// rehearsals.
		/// </summary>
		STAGE_MANAGER,
		/// <summary>
		/// Use for an organization responsible for the development or enforcement of a
		/// standard.
		/// </summary>
		STANDARDS_BODY,
		/// <summary>
		/// Use for a person or organization who creates a new plate for printing by
		/// molding or copying another printing surface.
		/// </summary>
		STEREOTYPER,
		/// <summary>
		/// Use for a person relaying a story with creative and/or theatrical
		/// interpretation.
		/// </summary>
		STORYTELLER,
		/// <summary>
		/// Use for a person or organization that supports (by allocating facilities, staff,
		/// or other resources) a project, program, meeting, event, data objects, material
		/// culture objects, or other entities capable of support.
		/// </summary>
		SUPPORTING_HOST,
		/// <summary>
		/// Use for a person or organization who does measurements of tracts of land, etc.
		/// to determine location, forms, and boundaries.
		/// </summary>
		SURVEYOR,
		/// <summary>
		/// Use for a person who, in the context of a resource, gives instruction in an
		/// intellectual subject or demonstrates while teaching physical skills.
		/// </summary>
		TEACHER,
		/// <summary>
		/// Use for a person who is ultimately in charge of scenery, props, lights and
		/// sound for a production.
		/// </summary>
		TECHNICAL_DIRECTOR,
		/// <summary>
		/// Use for a person under whose supervision a degree candidate develops and
		/// presents a thesis, m√©moire, or text of a dissertation.
		/// </summary>
		THESIS_ADVISOR,
		/// <summary>
		/// Use for a person who prepares a handwritten or typewritten copy from original
		/// material, including from dictated or orally recorded material. For makers of
		/// pen-facsimiles, use Facsimilist [fac].
		/// </summary>
		TRANSCRIBER,
		/// <summary>
		/// Use for a person or organization who renders a text from one language into
		/// another, or from an older form of a language into the modern form.
		/// </summary>
		TRANSLATOR,
		/// <summary>
		/// Use for a person or organization who designed the type face used in a
		/// particular item.
		/// </summary>
		TYPE_DESIGNER,
		/// <summary>
		/// Use for a person or organization primarily responsible for choice and
		/// arrangement of type used in an item. If the typographer is also responsible for
		/// other aspects of the graphic design of a book (e.g., Book designer [bkd]),
		/// codes for both functions may be needed.
		/// </summary>
		TYPOGRAPHER,
		/// <summary>
		/// Use for the name of a place where a university that is associated with a
		/// resource is located, for example, a university where an academic dissertation
		/// or thesis was presented.
		/// </summary>
		UNIVERSITY_PLACE,
		/// <summary>
		/// Use for a person or organization in charge of a video production, e.g. the
		/// video recording of a stage production as opposed to a commercial motion picture.
		/// The videographer may be the camera operator or may supervise one or more camera
		/// operators. Do not confuse with cinematographer.
		/// </summary>
		VIDEOGRAPHER,
		/// <summary>
		/// Use for a person or organization who principally exhibits singing skills in a
		/// musical or dramatic presentation or entertainment.
		/// </summary>
		VOCALIST,
		/// <summary>
		/// Use for a person who verifies the truthfulness of an event or action.
		/// </summary>
		WITNESS,
		/// <summary>
		/// Use for a person or organization who makes prints by cutting the image in
		/// relief on the end-grain of a wood block.
		/// </summary>
		WOOD_ENGRAVER,
		/// <summary>
		/// Use for a person or organization who makes prints by cutting the image in
		/// relief on the plank side of a wood block.
		/// </summary>
		WOODCUTTER,
		/// <summary>
		/// Use for a person or organization who writes significant material which
		/// accompanies a sound recording or other audiovisual material.
		/// </summary>
		WRITER_OF_ACCOMPANYING_MATERIAL,
		code,
		name

	}//end Relator

}//end namespace domain