///////////////////////////////////////////////////////////
//  ResourceReference.cs
//  Implementation of the Class ResourceReference
//  Generated by Enterprise Architect
//  Created on:      02-ÎåÔÂ-2012 16:21:05
//  Original author: lanfengqi
///////////////////////////////////////////////////////////


using System;
using nl.siegmann.epublib.domain;
namespace nl.siegmann.epublib.domain {
    [Serializable]
	public class ResourceReference  {

		protected Resource resource;
		private static readonly long serialVersionUID = 2596967243557743048L;

		/// 
		/// <param name="resource"></param>
		public ResourceReference(Resource resource)
		{
		    this.resource = resource;
		}

		public Resource getResource(){

			return this.resource;
		}

		/// <summary>
		/// The id of the reference referred to.  null of the reference is null or has a
		/// null id itself.
		/// </summary>
		public string getResourceId(){

            if (resource != null)
            {
                return resource.getId();
            }
            return null;
		}

		/// <summary>
		/// Besides setting the resource it also sets the fragmentId to null.
		/// </summary>
		/// <param name="resource">resource</param>
		public void setResource(Resource resource)
		{
		    this.resource = resource;
		}

	}//end ResourceReference

}//end namespace domain