///////////////////////////////////////////////////////////
//  TitledResourceReference.cs
//  Implementation of the Class TitledResourceReference
//  Generated by Enterprise Architect
//  Created on:      02-ÎåÔÂ-2012 16:21:08
//  Original author: lanfengqi
///////////////////////////////////////////////////////////


using System;
using nl.siegmann.epublib.domain;
namespace nl.siegmann.epublib.domain {
    [Serializable]
	public class TitledResourceReference : ResourceReference {

		private string fragmentId;
		private static readonly long serialVersionUID = 3918155020095190080L;
		private string title;

		public TitledResourceReference(){

		}

		~TitledResourceReference(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="resource"></param>
		public TitledResourceReference(Resource resource){

		}

		/// 
		/// <param name="resource"></param>
		/// <param name="title"></param>
		public TitledResourceReference(Resource resource, string title){

		}

		/// 
		/// <param name="resource"></param>
		/// <param name="title"></param>
		/// <param name="fragmentId"></param>
		public TitledResourceReference(Resource resource, string title, string fragmentId){

		}

		/// <summary>
		/// If the fragmentId is blank it returns the resource href, otherwise it returns
		/// the resource href + '#' + the fragmentId.
		/// </summary>
		public string getCompleteHref(){

			return "";
		}

		public string getFragmentId(){

			return "";
		}

		public string getTitle(){

			return "";
		}

		/// 
		/// <param name="fragmentId"></param>
		public void setFragmentId(string fragmentId){

		}

		/// 
		/// <param name="resource"></param>
		/// <param name="fragmentId"></param>
		public void setResource(Resource resource, string fragmentId){

		}

		/// <summary>
		/// Sets the resource to the given resource and sets the fragmentId to null.
		/// </summary>
		/// <param name="resource"></param>
		public void setResource(Resource resource){

		}

		/// 
		/// <param name="title"></param>
		public void setTitle(string title){

		}

	}//end TitledResourceReference

}//end namespace domain