///////////////////////////////////////////////////////////
//  ResourceUtil.cs
//  Implementation of the Class ResourceUtil
//  Generated by Enterprise Architect
//  Created on:      08-ÎåÔÂ-2012 16:02:45
//  Original author: paul
///////////////////////////////////////////////////////////


using System;
using System.IO;
using File = System.IO.File;
using Ionic.Zip;
using nl.siegmann.epublib.domain;
namespace nl.siegmann.epublib.util
{
    /// <summary>
    /// Various resource utility methods
    /// </summary>
    public class ResourceUtil
    {

        public virtual void Dispose()
        {

        }

        /// 
        /// <param name="file"></param>
        //public static Resource createResource(File file)
        //{

        //    return null;
        //}

        /// <summary>
        /// Creates a resource with as contents a html page with the given title.
        /// </summary>
        /// <param name="title"></param>
        /// <param name="href"></param>
        public static Resource createResource(String title, String href)
        {

            return null;
        }

        /// <summary>
        /// Creates a resource out of the given zipEntry and zipInputStream.
        /// </summary>
        /// <param name="zipEntry"></param>
        /// <param name="zipInputStream"></param>
        public static Resource createResource(ZipEntry zipEntry, ZipInputStream zipInputStream)
        {
            return new Resource(zipInputStream, zipEntry.FileName);

        }



    }//end ResourceUtil

}//end namespace util