///////////////////////////////////////////////////////////
//  PackageDocumentBase.cs
//  Implementation of the Class PackageDocumentBase
//  Generated by Enterprise Architect
//  Created on:      08-ÎåÔÂ-2012 16:08:02
//  Original author: paul
///////////////////////////////////////////////////////////


using System;

namespace nl.siegmann.epublib.epub
{
    /// <summary>
    /// Functionality shared by the PackageDocumentReader and the
    /// PackageDocumentWriter
    /// </summary>
    public class PackageDocumentBase
    {
        protected class DCTags
        {
            public static String title = "title";
            public static String creator = "creator";
            public static String subject = "subject";
            public static String description = "description";
            public static String publisher = "publisher";
            public static String contributor = "contributor";
            public static String date = "date";
            public static String type = "type";
            public static String format = "format";
            public static String identifier = "identifier";
            public static String source = "source";
            public static String language = "language";
            public static String relation = "relation";
            public static String coverage = "coverage";
            public static String rights = "rights";
        }

        protected class DCAttributes
        {
            public static String scheme = "scheme";
            public static String id = "id";
        }//end DCAttributes

        protected class OPFTags
        {
            public static String metadata = "metadata";
            public static String meta = "meta";
            public static String manifest = "manifest";
            public static String packageTag = "package";
            public static String itemref = "itemref";
            public static String spine = "spine";
            public static String reference = "reference";
            public static String guide = "guide";
            public static String item = "item";
        }//end OPFTags

        protected class OPFAttributes
        {
            public static String uniqueIdentifier = "unique-identifier";
            public static String idref = "idref";
            public static String name = "name";
            public static String content = "content";
            public static String type = "type";
            public static String href = "href";
            public static String linear = "linear";
            public static String _event = "event";
            public static String role = "role";
            public static String file_as = "file-as";
            public static String id = "id";
            public static String media_type = "media-type";
            public static String title = "title";
            public static String toc = "toc";
            public static String version = "version";
            public static String scheme = "scheme";
        }//end OPFAttributes

        protected class OPFValues
        {
            public static String meta_cover = "cover";
            public static String reference_cover = "cover";
            public static String no = "no";
            public static String generator = "generator";
        }//end OPFValues

        public static readonly String BOOK_ID_ID = "BookId";
        public static readonly String dateFormat = "yyyy-MM-dd";
        public static readonly String NAMESPACE_DUBLIN_CORE = "http://purl.org/dc/elements/1.1/";
        public static readonly String NAMESPACE_OPF = "http://www.idpf.org/2007/opf";
        public static readonly String PREFIX_DUBLIN_CORE = "dc";
        public static readonly String PREFIX_OPF = "opf";


    }//end PackageDocumentBase

}//end namespace epub